
<!DOCTYPE html>
<html>
<head>
    <title>System Backup Log Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 14px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .report-title { font-size: 22px; font-weight: bold; color: #1a56db; }
        .meta-info { margin-bottom: 20px; font-size: 12px; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { bg-color: #f3f4f6; font-weight: bold; }
        .badge { background-color: #e1f5fe; color: #0288d1; padding: 3px 8px; border-radius: 4px; font-size: 12px; }
        .img-container { text-align: center; margin-top: 5px; }
        .backup-img { width: 150px; height: auto; border: 1px solid #ccc; border-radius: 4px; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>

    <div class="header">
        <div class="report-title">System Backup Log Report</div>
        <div class="meta-info">
            Generated By: {{ auth()->user()->name }} <br>
            Date Generated: {{ now()->format('M d, Y h:i A') }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 15%;">Type</th>
                <th style="width: 30%;">Backup Date & Time</th>
                <th style="width: 50%;">Confirmation Attachment Proof</th>
            </tr>
        </thead>
        <tbody>
            @foreach($backups as $backup)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td><span class="badge">{{ $backup->backup_type }}</span></td>
                    <td>{{ \Carbon\Carbon::parse($backup->backup_datetime)->format('M d, Y h:i A') }}</td>
                    <td>
                        @if($backup->image)
                            <div class="img-container">
                                <img src="{{ public_path('uploads/backups/' . $backup->image) }}" class="backup-img" alt="Proof Photo">
                            </div>
                        @else
                            <span style="color: #999;">No image attached</span>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>